import type { PublicAppliance } from "./types";

const now = Date.now();

// Mirrors fictional development seed records; never used when Supabase is configured.
export const developmentAppliances: PublicAppliance[] = [
  [
    "dev_qr_refrigerator_000001",
    "DEV-R001",
    "refrigerator",
    "Northstar",
    "NRF-36",
    "stainless",
    "stainless",
    36,
    "electric",
    "refurbished",
    65000,
    "A roomy French-door refrigerator with a clean stainless finish.",
  ],
  [
    "dev_qr_washer_00000000001",
    "DEV-W002",
    "washer",
    "Harbor",
    "HWT-27",
    "white",
    "painted",
    27,
    "electric",
    "used",
    37500,
    "A straightforward top-load washer prepared for everyday laundry.",
  ],
  [
    "dev_qr_dryer_000000000001",
    "DEV-D003",
    "dryer",
    "Harbor",
    "HDE-27",
    "white",
    "painted",
    27,
    "electric",
    "refurbished",
    32500,
    "An electric dryer with simple controls and a bright white finish.",
  ],
  [
    "dev_qr_range_000000000001",
    "DEV-S004",
    "range",
    "Hearthline",
    "HGR-30",
    "black",
    "enameled",
    30,
    "gas",
    "used",
    45000,
    "A practical gas range with a black finish.",
  ],
  [
    "dev_qr_freezer_0000000001",
    "DEV-F005",
    "freezer",
    "Cold Creek",
    "CCF-21",
    "white",
    "painted",
    33,
    "electric",
    "refurbished",
    42500,
    "A chest freezer ready for extra frozen storage.",
  ],
  [
    "dev_qr_laundry_center_001",
    "DEV-L006",
    "laundry-center",
    "Stackwell",
    "SWC-24",
    "white",
    "painted",
    24,
    "electric",
    "used",
    57500,
    "A space-saving stacked laundry center.",
  ],
  [
    "dev_qr_misc_dishwasher_01",
    "DEV-M007",
    "miscellaneous",
    "Clearwater",
    "CDW-24",
    "black",
    "enameled",
    24,
    "electric",
    "refurbished",
    27500,
    "A compact dishwasher with an easy-clean black front.",
  ],
].map((row, index) => ({
  publicId: row[0] as string,
  inventoryNumber: row[1] as string,
  category: row[2] as string,
  brand: row[3] as string,
  model: row[4] as string,
  color: row[5] as string,
  finish: row[6] as string,
  widthInches: row[7] as number,
  fuelType: row[8] as string,
  condition: row[9] as string,
  priceCents: row[10] as number,
  description: row[11] as string,
  currency: "usd",
  availableAt: new Date(now - index * 86400000).toISOString(),
  photos: [],
}));
